---
name: Docker

on:
  push:
    branches:
      - main
    paths:
      - "**"

  pull_request:
    paths:
      - "Dockerfile"
      - "Requirements.txt"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and Push latest Docker image tag
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: digitalearthafrica/cube-in-a-box
          image_tag: latest
          username: gadockersvc
          password: ${{ secrets.GADOCKERSVC_PASSWORD }}
          push_image_and_stages: on:push

      - name: Copy a folder to s3
        uses: prewk/s3-cp-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          aws_access_key_id: ${{ secrets.GA_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.GA_AWS_SECRET_ACCESS_KEY }}
          source: 'cube-in-a-box-cloudformation.yml'
          dest: 's3://deafrica-dev-cfn/cube-in-a-box/cube-in-a-box-cloudformation.yml'
          flags: --acl public-read
          aws_region: 'af-south-1'
